### ISSUE TITLE
Thorough code review

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#107]
Make it *all* nice.

**Comment by rrthomas** [comment]
Rationale for tagging this 0.1 is that the code has been changing rapidly, rather than slowing down as one might hope before a release, so we can expect to find a number of nits and maybe even obvious bugs.

**Comment by apt1002** [comment]
Check the compilation logs of Travis and AppVeyor for warnings.

**Comment by rrthomas** [comment]
Check FIXMEs.

**Comment by apt1002** [comment]
Progress report: we have reviewed the Python modules (NOT scripts) except for stack.py, memory.py and assembler.py.

**Comment by apt1002** [comment]
Progress report: Made pull request #266; assembler.py remains TODO.

**Comment by apt1002** [comment]
Progress report: Finished reviewing the Python bindings.

**Comment by rrthomas** [comment]
Closing as agreed in December. There's no compelling reason to make a 0.1 release, and the code is continuing to evolve. The review was a useful exercise, so we should repeat it when we do come to make a release.
