### ISSUE TITLE
Feature request: instructions with immediate operands.

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#115]
In a comment on #92, @rrthomas wrote:

> I think Beetle was right: BRANCH[Z], CALL and LIT should have "immediate" versions that offer an argument in the remainder of the instruction word. [...]

The idea is to define four new opcodes: CALLI, BRANCHI, BRANCHZI and LITI. These opcodes have in common that they use the value of the I register as an immediate operand (and that they finish by performing the action of NEXT to reload I).

 To think about:

 - [ ] The expected benefits are denser code, faster code, and code that is easier to generate. An important use-case is code consisting mainly of CALL instructions, which is commonly emitted by pForth.

 - [ ] Do we really want all of them? Just CALLI might give most of the benefit.

 - [ ] How is the immediate operand encoded? E.g. Where is the sign bit? Is it PC relative? Is it multiplied by WORD_SIZE?

 - [ ] What instructions can be removed in return? E.g. Do we still need LIT_PC_REL? CALL? BRANCHZ?

 - [ ] When generating code, it is often necessary to patch the targets of forward references. Design the instruction set so that patching is easy, regular, and free of failures such as range limitations.

 - [ ] The instruction set should not require extra justification. If a pattern emerges among the opcodes, do not omit any opcode suggested by the pattern.

**Comment by apt1002** [comment]
Also on #92, @apt1002 wrote:

> CALL is the big win. If you have an immediate form of BRANCH, then the non-immediate form is just RET, which would certainly be needed anyway. Presumably immediate BRANCH and CALL would be PC-relative. Together they perhaps obviate LITW_PC_REL (the remaining rare cases can be handled using a subroutine). Non-immediate CALL can be implemented as a pair of subroutines (one PC-relative and one not) and does not warrant an opcode. I don't like immediate LIT because it is not terminal; better to segregate opcodes and literal data into separate words. I don't mind immediate BRANCHZ so much but I'm still against it. In summary, I think a suitable design would have LITW, BRANCHZ unchanged; LITW_PC_REL removed; immediate PC-relative BRANCH and CALL added; the existing BRANCH renamed to RET; and the existing CALL removed.

This approaches a concrete design, but @rrthomas felt it doesn't tick all the boxes above.

**Comment by apt1002** [comment]
Another concrete design would be to add CALLI, remove CALL, and leave it at that.

**Comment by rrthomas** [comment]
Indirect call: most sorts of late binding would naturally use this, e.g. vtables.

I'm not really interested in making code dense as such, just not unnecessarily wasteful of space.

For reasonable range of addresses, patching the remainder of a word after a one-byte opcode is fine.

I think I had a different definition of "terminal" in my head from yours. I meant "execution does not proceed past this instruction by incrementing PC", whereas it seems you mean "no more opcodes in the current word".

Conclusion: I think we're close enough to agreement and what I have in mind is simple enough that I'll just do it and we then have something concrete to discuss.

**Comment by apt1002** [comment]
For indirection through a method table, you might want a different instruction again, to set up `self` for example. I think the SMitish way to do this is using a subroutine that tailcalls the method.

**Comment by rrthomas** [comment]
We're not going to change anything else here.
