### ISSUE TITLE
Express non-aliasing guarantees

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#116]
Suppose `S` is a smite_state *. We know, but the compiler doesn't, that `S`, `S->memory` and `S->S0` are disjoint. This knowledge allows us to allocate registers for the three values, and for various other fields of `S`, and to cache stack slots in local variables. The compiler should be able to do that too.

I've been reading about the "restrict" keyword. https://en.cppreference.com/w/c/language/restrict

I think what is required is to annotate the following pointers with "restrict":
 - `S` on entry to `smite_single_step()` and `smite_run()`, and maybe some others.
 - `memory` and `S0` in the declaration of `struct smite_state`.

**Comment by rrthomas** [comment]
Thanks for this, excellent. It seems to me this can be done independent of changes to the instruction set; would you like to prepare a PR?

**Comment by apt1002** [comment]
Branch issue116. Experimental. Needs benchmarks and other analysis.

**Comment by apt1002** [comment]
I don't think we should merge this. It doesn't seem to make things go faster.

I'll leave the branch hanging around. It's pretty easy to maintain, because the diff is very small.

**Comment by rrthomas** [comment]
It would be nice to know why it doesn't work, given we thought it should.

**Comment by apt1002** [comment]
We got bored of maintaining the branch. We decided to merge it rather than delete it.
