### ISSUE TITLE
Cannot bootstrap

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#119]
I'm using master as of 5th April (db7824023b9f2a50a6751313f35f0ea0be094d05), running on Ubuntu 16.04 LTS.

The command "./bootstrap" fails with the following error:

```
bootstrap: running: autoreconf --symlink --install
aclocal: error: aclocal: file 'm4/std-gnu11.m4' does not exist
autoreconf: aclocal failed with exit status: 1
```

"apt-file search" cannot find any package containing the file "std-gnu11.m4".

**Comment by rrthomas** [comment]
That's a gnulib file. Did you try a fresh clone of smite?

-- 
https://rrt.sc3d.org

**Comment by rrthomas** [comment]
Further, I can confirm that file is in the checked-in commit of the gnulib submodule.

**Comment by apt1002** [comment]
I too have the file in "gnulib/m4". Odd.

A fresh clone works. Presumably the problem is caused by some file left over from a previous version. Any idea what?

I cannot make dist-clean, because I cannot bootstrap. My copy of the repo is effectively dead. I'll start again from a fresh checkout.

**Comment by rrthomas** [comment]
The most obvious thing would be a broken symlink to a local clone of gnulib, but I don't think you ever set up a local clone of gnulib for bootstrap to use.

Closing, absent further compelling evidence of a bug.
