### ISSUE TITLE
Redo literal value popularity measurement

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#124]
Last time we measured the popularity of literal values, 0 and 1 were the winners by a significant margin. We created opcodes for them. This is important for two main reasons:

 - Code density. We save a whole word each time these opcodes are used. We save even more if the compiler doesn't interleave instructions and words fully.
 - Specialization. Using an opcode cheaply allows the specialized interpreter to know the value at the top of the stack, which can be important.

Since then, the instruction set has changed a bit. SWAP and POP take stack positions off the top of the stack, and LOAD, STORE and SIGN_EXTEND take sizes, which are often 2 or 3.

We should redo the measurement, and consider adding opcodes for literals 2 and 3.

**Comment by rrthomas** [comment]
Happy to wait until we're generating code for more-mainstream languages

**Comment by apt1002** [comment]
#160 allocates opcodes for `LIT_2` and `LIT_3`.

**Comment by rrthomas** [comment]
Closing: we will no doubt be remeasuring the popularity of the `LIT_n` instructions and other literal values again in future as things evolve.

**Comment by apt1002** [comment]
From #176:
 - LIT 13.1%
 - LIT_2 12.4%
 - LIT_0 7.4%

These are expressed as fractions of all instructions executed. LIT_1 and LIT_3 are below 3%.

The test case was booting pForth, which is not particularly representative. The hottest traces were the function prologue and epilogue strings, in which are found LIT_0 DUP, LIT_2 LOAD and LIT_2 STORE. The most common use of LIT_1 was before SWAP. LIT (with constants not in {0, 1, 2, 3}) was used before CALL (various subroutine addresses), LOAD (mainly the address of the RSP variable) and ADD (mainly 4 and –4?).

While this tells us about pForth, I think it also tells us a bit about Mit. I expect the importance of the DUP, SWAP, LOAD and STORE use cases will replicate. For 64-bit test cases it seems likely that LIT_3 will take some probability away from LIT_2.
