### ISSUE TITLE
Add `PUSH_STACK_DEPTH` back

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#150]
This is needed for sandboxed operation in a way that knowing how big memory is is not, e.g. for exception handling code.

**Comment by apt1002** [comment]
I don't understand. Please can you explain in more detail?

**Comment by rrthomas** [comment]
We'd like to use SMite to run sandboxed code. In theory that just means "no access to libc", but I'd suggest it'd be much easier to make it correct if it also meant "no access to libsmite". Hence no way currently to read `STACK_DEPTH`, which is really needed to implement exception handling within a program, even something simple like pForth's "return to top level and clear the stack". Setting `STACK_DEPTH` can be achieved by `POP` and some calculation.
