### ISSUE TITLE
Make more use of A_FALLBACK to simplify the rare code paths

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#164]
The specializer no longer tries to be a complete replacement for smite_run; its A_FALLBACK label calls `smite_single_step()` to achieve correct behaviour in cases that are not worth optimizing. Currently this only includes the `EXT` instruction and illegal instructions. We could also use A_FALLBACK in a few other cases:

 - [x] Stack underflow and overflow.
 - [x] Maybe even variadic instructions? These should be rare after #126.

The general idea is that when the specializer guesses the next instruction, if it can't guarantee the simple fast path will work, it behaves as if it guessed wrong.

**Comment by apt1002** [comment]
On branch "specializer", we no longer guess variadic instructions unless the top stack item is a known constant. Thanks to @rrthomas's recent improvements to pForth (#176) this results in a slowdown of less than 1%.

**Comment by apt1002** [comment]
We now use `A_FALLBACK` for all extra instructions (internal & external).

**Comment by rrthomas** [comment]
Overflow and underflow checks made it slightly slower, if anything, but we did it anyway as they simplify the code.
