### ISSUE TITLE
`BRANCHZ` may not currently be followed by another instruction in the same word

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#170]
Because `NEXT` checks that `I` is 0, and raises an error for an invalid opcode if it is non-zero, `BRANCHZ` may not be followed by another instruction in the same word.

I believe this is unintentional (in particular, `BRANCHZ` is not in the "terminal" set in the assembler). But is it worth changing? In particular, it would require special treatment (or yet another permutation of the order of the execution loop). Or, we can just pull the zero check back into the "terminal" instructions.

One final option is to have `BRANCHZ` explicitly set `I` to 0 when it takes the branch. That seems the neatest solution to me.

**Comment by apt1002** [comment]
You are right, it is unintentional. I agree the best solution is for BRANCHZ to set both PC and I.

**Comment by rrthomas** [comment]
Fixed.
