### ISSUE TITLE
Add Brainfuck tests

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#173]
This is a cheap way to get some more benchmarks and test cases.

**Comment by apt1002** [comment]
https://github.com/pablojorge/brainfuck/blob/master/README.md <-- Some Brainfuck benchmarks and competing Brainfuck implementations, both interpreted and compiled.

**Comment by rrthomas** [comment]
https://gist.github.com/rrthomas/3f18eb8904ae35aaf28cf9fe5bfb6e57

**Comment by apt1002** [comment]
"mandelbrot.bf" compiled to Mit object code and interpreted using the "mit" command: 6m43s.
"mandelbrot.bf" interpreted by a Rust program: 1m7s.

It is, of course, completely ridiculous to draw Mandelbrot sets using a language with no addition, let alone multiplication.

**Comment by rrthomas** [comment]
See branch `brainfuck`.

**Comment by apt1002** [comment]
More Brainfuck compilers.

 - https://github.com/rdebath/Brainfuck/tree/master/tritium <-- Fastest, apparently.
 - http://www.wilfred.me.uk/blog/2015/08/29/an-optimising-bf-compiler/
 - https://github.com/brianquinlan/brainfuck-jit/blob/master/bf_compile_and_go.cpp

And others: https://esolangs.org/wiki/Brainfuck#Notable_implementations

**Comment by rrthomas** [comment]
Is it worth adding these to the test suite? If so, I suggest adding a subdirectory to tests with a suitable test harness that can run a brainfuck program and compare its output against expected output. I can do this based on the test harness for `tests/hello.py`, and also collect timings; tests should be divided into those that should always be run, and long-running performance tests.
