### ISSUE TITLE
Install machine-readable (YAML? JSON?) metadata

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#180]
Rather than force other programs to use the C library directly, or to install secondary (e.g. Python) bindings for easier access, install machine-readable description of the VM, which can itself be primary (used to generate the C as well as Python). See issue #96.

**Comment by apt1002** [comment]
JSON would be my choice, I think.

**Comment by rrthomas** [comment]
Depends on #52.

**Comment by rrthomas** [comment]
Closed by merging branch spec-to-data-52.
