### ISSUE TITLE
Examine code generation for naive single_step

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#183]
I noticed that the specializer is faster than naive `single_step` even with an empty trace. The only difference then is that the specializer is executing a series of ifs rather than a switch.

It's probably time to refresh our knowledge of vmgen, do some experiments and look at the assembler output, and probably abstract the control flow of the naive interpreter, and have more than one way of generating it. Another obvious optimisation would be to have "specializer lite", ordering a list of ifs according to decreasing instruction frequency.

And in fairness, such changes ought to be applied to Beetle!

**Comment by rrthomas** [comment]
Some comparisons (the relative timings here are more interesting than the absolute differences between CPUs):

i5 Sandy Bridge: `mit`: 12s; `mit -O`: 9s
i5 Haswell: `mit`: 8s; `mit -O`: 6s
Qualcomm MSM8998: `mit`: 15s; `mit -O`: 17s

**Comment by rrthomas** [comment]
A related article: https://www.pvk.ca/Blog/2012/07/03/binary-search-star-eliminates-star-branch-mispredictions/ (but it is about search for non-contiguous values where the key might not be found).

**Comment by apt1002** [comment]
i5 Haswell (mentioned above) is a 15W chip, right? And i5 Sandy Bridge is 65W?

**Comment by rrthomas** [comment]
Haswell: probably, it's a laptop. Sandy Bridge: no, that's low power too; my PC's power budget is supposed to be ~30W.

**Comment by apt1002** [comment]
65W i5 Sandy Bridge: mit 9.6s; mit -O 6.9s

(With a trace file made by booting pForth, it's 3.18s, but that's irrelevant to this issue).

In the short term, this might be a faster but still platform-neutral way of dispatching instructions:
```
if (opcode == NEXT) ...
else if (opcode == LIT) ...
else if (opcode == CALL) ...
else switch (opcode) ...
```

**Comment by apt1002** [comment]
@rrthomas rewrote `single_step()` using "if"s and ordering the instructions by popularity. It's nearly twice as fast. This in turn makes "mit -O" about 6% faster.

**Comment by rrthomas** [comment]
Review completed. We found some bugs and a real performance puzzle (see commit a81eacd3).
