### ISSUE TITLE
Word-specific `load()`

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#193]
Options:

- [x] Use `__always_inline__` attribute on `load`: this seemed to have no effect beyond warnings that the function "might not always be inlinable". 
- [x] Do it manually in some form.

This is principally for loading from `PC` in `NEXT`, `LIT` and `LIT_PC_REL`. The existing `load()` switches on the word size, and is big enough that GCC doesn't inline it everywhere.

Also elide alignment check for loading from `PC` which we know to be aligned (instructions that set `PC` need to add the check)

**Comment by apt1002** [comment]
We might be able to meet the requirement using the existing `native_address_of_range()` function.

**Comment by rrthomas** [comment]
Good point; would you like to try that?

**Comment by rrthomas** [comment]
Tried it, didn't work, used a simple macro.
