### ISSUE TITLE
Make registers locals (via macros)

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#195]
Attempt to reduce memory traffic in `mit_single_step` etc.

I imagine that to be effective in `mit_run`, `mit_single_step` will need to be inlined into `mit_run`?

**Comment by apt1002** [comment]
Maybe `mit_single_step(S)` should call `inner_run(S, TRUE)` and `mit_run(S)` should call `inner_run(S, FALSE)`, where:
```
mit_word inner_run(mit_state *S, bool single_step) {
    // ...
    do {
        // Dispatch one instruction.
    } while (res == 0 && !single_step);
    // ...
}
```
? This avoids a second copy of the dispatch code.

**Comment by rrthomas** [comment]
Fiixed by #207.
