### ISSUE TITLE
Enforce a lower bound on the memory size

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#197]
It would be useful to be able to assume that the maximum number of program words that can be read between terminal instructions is smaller than the total memory size. With 4-bit instructions and 256-bit words, 2080 bytes would suffice. For 5-bit instructions and 128-bit words, 432 bytes would suffice.

The code to check that all the words are within memory requires two comparisons without this assumption (start <= memory_size && len <= memory_size - start), but with the assumption only one comparison is required (start <= memory_size - len).

**Comment by rrthomas** [comment]
I don't think this need be part of the spec, but it makes sense to add it as a constraint to the implementation; patch welcome!

**Comment by rrthomas** [comment]
Since the specializer can always fall back to the "core" implementation, it can add restrictions like this if desired.
