### ISSUE TITLE
gen-specializer can look for impossibly long traces

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#221]
For example, building with `WORD_BYTES` = 2:

    features/specializer.c:929:18: warning: comparison is always false due to limited range of data type [-Wtype-limits]
             if (S->I == 0x1080e && likely(1) && likely((S->stack_size - S->STACK_DEPTH) >= 1)) {
                      ^~

**Comment by rrthomas** [comment]
@apt1002, do you have a fix for this?

**Comment by rrthomas** [comment]
I realize that the problem here is that the trace being used is for the wrong word length (and hence useless anyway). Presumably we should record `WORD_BYTES`, `OPCODE_BIT` and `ENDISM` in the predictor, and fall back to an empty predictor for those combinations for which we don't have a checked-in predictor.

**Comment by apt1002** [comment]
I think I can fix this in gen-labels.

I think using a trace for the wrong `WORD_BYTES` is better than nothing.
