### ISSUE TITLE
`mit_max_stack_item_t` can be too small

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#239]
On Win32, for example, `off_t` is 8 bytes, but `size_t` is only 4. Therefore `mit_max_stack_item_t` is too small, as it cannot hold a `off_t` (in `extra_instructions.c`).

Solution: use `intmax_t`'s size instead of `size_t`'s.

Fix already pending; check against AppVeyor MINGW32 build log.

**Comment by rrthomas** [comment]
Confirmed fixed (no warning about invalid shifts in AppVeyor MINGW32 build log https://ci.appveyor.com/project/rrthomas/mit/builds/25401554/job/99so9o9jdteipagg )
