### ISSUE TITLE
Improvements to the memory model

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#24]
The current memory model is good for in-process Mit, and offers global efficiency in use of memory (because native memory can be arbitrarily mapped on to the VM) and new blocks of memory can be mapped into the address space without reallocation.

However, it's slow: individual memory accesses require a software memory manager. There are two slow-downs:

1. **Bounds checking**, which is desirable in in-process/multi-instance Mit. (When Mit runs in a dedicated process, can rely on the kernel instead.) However, simple bounds checking (`addr < LIMIT`) can be retained in most circumstances.
2. **Address translation**, which is required when the native and VM address sizes differ, or when VM code can't be relocated. Simple address translation (memory pointer plus offset) can be retained in most circumstances.

It would be good to make both of these optional. In order to achieve this:

- [X] Fix argc/argv `EXTRA` instructions to work well without a memory map.
- [X] Move the stacks out of memory altogether (i.e. their locations no longer have addresses).
- [x] Remove memory area API, and have just what is currently called "main memory".
- [x] Factor memory management code into basic load/store instructions plus the ability to resize the VM memory, plus an "address translation" plugin and a "bounds checking" plugin (effectively Beetle's `CHECKED`) to that (so it's not possible to have bounds checking without address translation; there's little point).

**Comment by rrthomas** [comment]
Further, multi-state SMite only make sense with the current scheme (call it 0) and scheme 1 above.

It would be great to have these as add-ons to a simple base.

**Comment by rrthomas** [comment]
When using a raw memory model, Mit's stack could be merged with the system stack. This avoids the need for malloc.

**Comment by apt1002** [comment]
#276 has some ideas.

**Comment by rrthomas** [comment]
This is complete for now. Not everything has been done. Address translation and bounds checking will not be added back. Also, the stack cannot be merged with the system stack conveniently any longer as that does not permit the use of one state as an error handler for another (effectively a coroutine, unless the inner stack is destroyed on error, which reduces the utility of the error handler considerably).
