### ISSUE TITLE
Building pforth test in src fails

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#254]
Not found by travis due to #253.

**Comment by rrthomas** [comment]
I cannot reproduce this (the problem was that the test to build pforth did not work.

I wonder if the tests are insufficiently isolated and somehow picking up an old libmit on your system?

**Comment by rrthomas** [comment]
@apt1002, could you possibly check this with current master?

**Comment by apt1002** [comment]
Mysterious. Can't reproduce on current master. Maybe I forgot to `./bootstrap`?
