### ISSUE TITLE
RLIT, RETZ

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#27]
I wonder if you should have an RLIT instruction that pushes a literal onto the return stack, and a RETZ instruction that returns from a subroutine conditionally? There are some knock-on simplifications:

- LIT BRANCH is just RLIT RET, i.e. you can remove BRANCH.
- LIT BRANCHZ is just RLIT RETZ, i.e. you can remove BRANCHZ.
- Although you can't implement BRANCH as 0 BRANCHZ (#5) you *can* implement RET as 0 RETZ.
- Unlike LIT, it is sensible for RLIT values to be always word-sized.
- Perhaps LIT only needs to handle small (e.g. signed 7-bit) constants, because large constants are available using RLIT RPOP.

Summary: +2 -3 distinct instructions; specialise LIT/RLIT.

**Comment by rrthomas** [comment]
Made irrelevant by #46.
