### ISSUE TITLE
Add configure switch to enable --profile

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#272]
Profiling slows things down (0.1s for ~10Ginstructions), so make it turn-offable.

**Comment by rrthomas** [comment]
I have a counter-proposal: add an extra entry point to `libmitfeatures` that is `mit_specializer_run` plus profiling, say, `mit_specializer_run_profiling`. Could also, à la profiler, add `mit_specializer_profiling_init` so it could be re-used.

**Comment by rrthomas** [comment]
Also, arguably the API should be the same as for the predictor, that is, taking a file descriptor to write to, rather than using a fixed filename. See also #273.
