### ISSUE TITLE
Group instructions into words

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#28]
One of the differences between SMite and Beetle is that SMite's instructions are encoded as a byte stream, whereas Beetle's are a word stream. This difference was deliberately introduced in order to simplify SMite. I think it hasn't worked and the change should be reverted, for the following reasons:

- The word-code makes the endianness invisible, but the byte-code exposes it. Reducing the number of incompatible versions of SMite you have to maintain and test is desirable.
- You don't need to byte-encode literals, so the complexity budget of packing instructions into words is paid off.
- Patching code addresses in pForth is easier in the word code, and the generated code is better. I was quite disappointed how many NOPs you have to leave in the byte code.
- The specialised interpreter would prefer to verify its guesses a whole word at a time. Doing so reduces the dispatch overhead and provides more opportunities for optimising the code. However, it makes interpreting unexpected code a bit less efficient.

**Comment by apt1002** [comment]
Furthermore, if you do pack instructions into words, the instructions do not need to be uniformly 8 bits in length. LIT 0 and LIT 1 deserve about 4 bits each, if I remember rightly, whereas the rarer instructions like DIV could be longer.

As in Beetle, NEXT (the instruction which fetches the next word of instructions) should have opcode ...00000000 so that it takes no space (all bits beyond 63 are implicitly zero anyway). CALL should have opcode ...00000001, because it is often the last instruction in a word, and this choice allows you to squeeze it into just one bit if necessary. Similarly, RET should be ...00000010.

**Comment by rrthomas** [comment]
I shall treat this in two comments. In the first (here), I shall come up with a list of requirements (mainly by addressing your list of points above), and in the second, with a design that I think satisfies the requirements.

- I propose to support both `ENDISM`s (and all `WORD_SIZE`s) in C SMite in any case: #73. (Endianness in Beetle is invisible at the cost of making byte access more expensive when running code on the other `ENDISM` for that for which it was compiled; I'm happy instead with giving the choice of a) compile for the `ENDISM` you want; b) translate the code at load-time (this requires extra conventions, but that will come with relocation, run-time linking etc.); c) interpret it directly and pay a penalty for all memory accesses.)
- Allowing variable-length instructions loses most of the complexity gain won from dropping the current literal encoding. (Also, we could do worse than study Martin Richards's various encodings for Cintcode to better understand the trade-offs; and anyway, perhaps a hyper-compact interpretive encoding is precisely where the sort of "plug-in encoding" I've talked about would be good.)

So I won't be deducing requirements from either of those.

Then what we want is:

- Faster, simpler literal encoding/decoding.
- Easy fast code generation (e.g. not worrying about how big a branch offset is). [Note that the current pForth back-end with `NOP`s can already be fixed by simply outputting numbers that are always maximum length, with leading sign bytes, so in fact it already satisfies this criterion for simplicity, if not for speed, as those numbers are not word-aligned words.]
- Ability for specializer to work on multiple instructions. (I suggest that this need not involve an actual word code; so sometimes the specializer might be wrong about what is code and what is actually data (or just garbage), but that would only affect speed, not correctness.)

**Comment by rrthomas** [comment]
Suggested design to meet the above objectives:

- Reintroduce `I` register (like Beetle's instruction accumulator), loading a word at a time, and `NOP` becomes `NEXT`.
- Replace numbers by the following instructions: `LIT`{`0`,`1`,`2`,…,`WORD_SIZE`÷2,`W`}[`_PCR`]. `PCR` means `PC`-relative, and the number indicates the number of extra bytes, which directly follow the opcode, except for `W`, where they are found in the next whole word.

Encoding:

- Instructions: as at present.
- Number: top bit 1, next bit set for "add PC", then the number of 1s gives the power of two number of literal bytes to follow. The remaining bits are used for the MSBs of the literal. In other words, possible literals are: 1x0[5 bits], 1x10[4 bits][1 byte], 1x110[3 bits][3 bytes], 1x1110[2 bits][4 bytes], […omitting the cases that only apply for larger `WORD_SIZE` than we currently implement…as a side note, this neatly fits (unintentionally!) the upper limit of 32] 1x111111 (that's the W case, where the next available word stores the entire literal).

A possible extra constraint would be that inline literals cannot straddle word boundaries, but I don't think that's worthwhile.

WDYT?

**Comment by apt1002** [comment]
ENDISM: fine. I prefer Beetle's design. Might as well fix it as little-endian for object files, and fix up in the loader and for byte accesses.

WORD_SIZE: also fine. My weak preference is to support 64-bit only.

**Comment by apt1002** [comment]
Variable-length encodings: I'm happy with 8 bits, or 6 bits, or whatever. Variable length is not hard, but we should probably require evidence of a problem before getting excited about a possible solution, so you are right.

Martin Richards: I think his optimization criteria were different from ours. He was not using 64-bit machines, and had different goals. His techniques require quite a bit of work. I don't think they are appropriate for SMite.

Update: On reflection, I'm warming to a Martin Richards encoding. We could allocate a 5-bit opcode range to each of POP, DUP, SWAP, ROTATE_UP, ROTATE_DOWN and LIT, and still have 64 opcodes to spare. This obviates variadic instructions and helps gen-actions to understand the stack operations.

**Comment by apt1002** [comment]
`I` register: yes! But wasn't it actually the `A` register in Beetle?

Numbers: I want the literal data in a separate word, unless I'm specializing for it. This could be achieved by supporting LIT0 and LITW only. This incidentally also achieves your extra constraint of not splitting literals across word boundaries.

Encoding: LITW and LITW_PCR belong with other instructions, so I would give them opcodes in the 0 to 63 range, and make them normal actions. LIT0_PCR is an interesting one; we could definitely do without it (and use LITW_PCR instead). If we do provide LIT0_PCR, we should only support multiples of WORD_SIZE. For absolute LIT0, numbers outside 0...3 are pretty rare, but I have no objection to supporting a larger range for simplicity. In all versions of LIT0 you should clarify the encoding of negative numbers.

**Comment by apt1002** [comment]
In general, code size is not an important optimization criterion, except in so far as it coincides with optimizing guard instructions.

**Comment by apt1002** [comment]
A nice way to express the encoding of LIT0 of a number `n` as `C+n` for some `C`. Works for negative numbers too, and has a good implementation. We could easily arrange `C==0` by renumbering the instructions out of the way, as they were a few months ago.

**Comment by apt1002** [comment]
That was rather rambling, sorry. Let me write a summary.

 - Yes to the `I` register.
 - Yes to fixed-length opcodes, and to bytes in particular.
 - Yes to LITW and LITW_PCR. I suggest that these are just ordinary action op-codes.
 - Yes to 1-byte encodings of small absolute literals. I suggest that these are encoded as `C+n`. A 5-bit unsigned `n` is more than enough; use INVERT for small negative numbers.
 - No to other literals. They have cost but no benefit. The specializer would mask out their values anyway, and would prefer the space in the `I` register to be used for more instructions instead.

**Comment by apt1002** [comment]
Suggestions:

- (Note that we now have a 6-bit instruction set.)
- Execute opcodes from LSB upwards (shift right after each decode).
- Encode CALL, RET, BRANCH, NEXT with high bits clear, so they can be encoded in fewer than 6 bits, and therefore fit in the remainder of a word.

**Comment by apt1002** [comment]
We talked about implementing Forth in one-stack SMite. This requires emulating the Forth return stack. Every function starts with a prologue that moves the return address from the SMite stack to the emulated return stack, and ends with an epilogue that moves it back again.

The obvious implementation of the prologue and epilogue is as subroutines. Here's a better one, using the 6-bit encoding proposed here and 32-bit words.

Addresses 0 and 4 are unavailable, so the smallest available address is 8. We use it to store the return stack pointer. It occupies one word.

The function prologue starts at address 12. It takes one argument, being the address of the function, and branches to it. Therefore, to call a function pointer on the top of the stack do 12 CALL. The code at address 12 is 8 LOAD STORE 8 LOAD (NEXT) 4 + 8 STORE BRANCH. It occupies two words.

The function epilogue starts at address 20. It pops the return address from the return stack and branches to it. To return from a function do 20 BRANCH. The code at address 20 is 8 LOAD 4 NEGATE ADD (NEXT) 8 STORE 8 LOAD LOAD BRANCH. It occupies two words.

**Comment by rrthomas** [comment]
I have done a somewhat sneakily lazy implementation of this on branch `word-encoding`. Let me know what you think, @apt1002!

It implements just `LITW` (as `LIT`) and `LITW_PCR` (as `LIT_PC_REL`). No one-byte literals. It's rather less dense than previously, but not much slower.

It sticks to a byte encoding.

The "sneaky" bit is that it does not reintroduce the `I` register, and in the current implementation, it's not a word encoding at all, really; it continues to load a byte at a time. However, I claim that it could be implemented with word-by-word loading, except there would be an issue with modifying the word currently being executed. There are various solutions to this, e.g. a) don't do it; b) forbid it in the spec; c) add a check to the `STORE` instructions.

What I like about this solution is that it does not complicate the spec (indeed, it's simpler than with the old encoding), yet it seems to be open to optimisation.

I'm a little unsure about one-byte literals. I am tempted to implement them as an extra, too.

PForth is working too; see branch `smite-word-encoding`.

**Comment by apt1002** [comment]
I like the instruction names.

I can see the attraction of a byte-encoding with padding bytes. However, I think the full word encoding with the I (or A) register is better, for the following reasons:

 - LIT is almost always followed by another instruction, so it is frustrating that the byte encoding makes you put padding bytes after it.
 - The byte encoding exposes the endianness of the host, but the word encoding doesn't.
 - The word encoding guarantees that PC is word-aligned at all times, but the byte encoding doesn't. This adds run time cost.
 - The specializer might need to guard on only part of a word. That's easy if it's the low bits of the I register, but it's not easy if it has to perform a memory access that depends on PC % WORD_SIZE.
 - The byte encoding is not compatible with 6-bit instructions.
 - The semantics of self-modifying code is muddier in the byte encoding than in the word-encoding, as you observe.

Summary: please can I have the I (or A) register?

**Comment by rrthomas** [comment]
Thanks for this. The following is intended not as haggling, but to see how far I can close the gap without doing anything (so I'm lazy, not miserly):

- There are no padding bytes. I did have them to start with, but got rid of them; have I left traces?
- The endianness is not exposed in the encoding (it's a straight byte code); it is exposed by `LOADB`/`STOREB`, but I'm happy with that because it means that native-endian code is not slowed down as it was with Beetle (where big-endian byte access is slow, and where the "DMA" interface is needed for I/O).
- The specializer can guard on whatever number of bytes it likes.
- 8-bit instructions aren't compatible with 6-bit in any case; in other words, using 6-bit (or variable-length) instructions would be a change to the encoding anyway; albeit a smaller change with the `I` register.

The rest of your points I grant. On the other hand:

- Adding `I` and forcing `PC` to be word-aligned complicates the simple implementation
- Word-alignment means that branch targets have to be word-aligned; but as seen with Beetle, or for that matter, ARM, that's not a big deal.
- A question: how does word-aligning `PC` reduce run-time cost?

So I think, yes, I will implement `I` (and we can then compare and contrast again); but I'm not keen to change the semantics of byte access. That means that instructions will be words of native-endian order bytes (as for Beetle), and access to individual bytes will give different results depending on `ENDISM`.

**Comment by apt1002** [comment]
Padding bytes: I think I must have seen the earlier version. I have now found LOAD_IMMEDIATE_WORD().

"native-endian code is not slowed down" <-- you mean the XOR 3 in LOADB and STOREB? That's a tiny cost. I take the point about DMA, though. If you see native endianness as a feature, rather than as a problem to be solved, then I suppose this point doesn't stand.

"The specializer can guard on whatever number of bytes it likes" <-- How? Loading the bytes individually, and concatenating them using arithmetic, you mean? I suppose that might be faster than guarding on individual bytes, but I think it will be a bottleneck.

"8-bit instructions aren't compatible with 6-bit in any case" <-- Do you mean there are now more than 64 opcodes?

"how does word-aligning PC reduce run-time cost?" <-- I was thinking of the call to `align()` in LIT, which no longer exists. Now I am thinking of LOAD_IMMEDIATE_WORD().

**Comment by rrthomas** [comment]
- Yes, I mean the XOR. That's a tiny cost for 1 byte, but a bottleneck for operating on blocks of memory. I would happily abstract endianness if it were performance neutral, but I don't think it is. For practical purposes today, one could assume little-endian and cover >90% of the market.
- I didn't mean there are now more than 64 opcodes. I meant that using 8-bit opcodes within a word is different from using 6-bit opcodes within a word. The fact that both are possible using a word encoding does not change the fact that they're different encodings. (As you say, it makes no sense to use a 6-bit encoding combined with a byte-code; I'm just saying that even with a word code you have to pick which you use.)
- `LOAD_IMMEDIATE_WORD` and instruction fetch could use word loading already (modulo the semantics issues highlighted above for self-modifying code). It might be interesting to see what the difference in performance is between such a scheme and reintroduction of the `I` register.

**Comment by apt1002** [comment]
"a bottleneck for operating on blocks of memory" <-- Really? I'm struggling to guess the inner loop you are imagining. `memcpy()`, I suppose. But written in SMite using byte access. And the native-endianness version gets vectorized but the little-endian version doesn't. Something like that? I think your desire to avoid special DMA operations to copy data to host memory is a better argument.

**Comment by apt1002** [comment]
6-bit: I'm losing track of this part of the conversation. Let me try to reboot.

The benefit of a 6-bit encoding is that you can fit 5+ instructions in a word, versus 4 instructions encoded as 8 bits. This benefit is not available if instructions are byte-aligned.

You seem keen to make a minimal change, which is understandable. There is a 6-bit encoding which preserves all the existing opcodes apart from 1-byte literals and opcode zero (needed for NEXT). However, for best results CALL and BRANCH should have opcodes less than four, as discussed earlier. This could be achieved by swapping the control-flow and stack manipulation instructions. Is there another aspect of the existing 8-bit encoding that you want to preserve?

**Comment by apt1002** [comment]
"could use word loading already" <-- How? unaligned?

**Comment by rrthomas** [comment]
The aspect of the 8-bit encoding I would like to preserve is that it uses whole bytes, so it's easier to work with. I agree this is not as important or useful in a word encoding as in a byte encoding.

A decoder can use word-loading already with unaligned loads (though I thought of it more as using aligned loads, shifts and masks).

**Comment by rrthomas** [comment]
Operating on blocks of memory: I mean that if you want native code to operate on SMite memory it had better be in native endianness (so yes, this is all about the DMA interface).

**Comment by apt1002** [comment]
Unaligned loads: I think your design decision not to require unaligned loads was a good one. Faking an unaligned load using aligned loads and shifts is problematic in corner cases (e.g. aligned load at the end of memory) as well as slow. The word encoding avoids these problems.

**Comment by apt1002** [comment]
"The aspect of the 8-bit encoding I would like to preserve is that it uses whole bytes, so it's easier to work with." <-- I concede this point.

I think the problem is confined to the assembler and disassembler (and compiler back ends which reimplement the assembler). I've written some code to show how it can be handled (branch "assembler"). It's not too bad. There's very little difference between the 8-bit and 6-bit designs, actually; the extra concepts come from having the I register.

In partial compensation for the extra code, you can forbid unaligned loads and delete the code (in class WordMemory) which implements them.

**Comment by apt1002** [comment]
May I reopen this issue until the I register is working?

**Comment by rrthomas** [comment]
Done!

**Comment by rrthomas** [comment]
(Note: the unaligned word load was slated for addition to the API, so that would have been removed from Python anyway!)
