### ISSUE TITLE
Uninitialised variable warning in specializer

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#287]
Clang reports this for the code generated by:

    while cache_state.cached_depth > 0:
        switch_code.append('case {}:'.format(cache_state.cached_depth))
        case_code = Code()
        case_code.extend(cache_state.flush(cache_state.cached_depth - 1))
        case_code.append('// Falls through.')
        switch_code.append(case_code)

The `state_`n variables (specifically here, `state_4` with current head of branch `appveyor-fixes`) can be uninitialised when flushed. Not a problem (?) but I guess we should turn off the warning explicitly?

**Comment by apt1002** [comment]
Interesting that GCC does not warn. On every path that reaches this `switch` the selector is a compile-time constant. Apparently GCC understands that and Clang does not.

I'm happy with suppressing this warning, but it might be better to initialise the variables to a dummy value.
