### ISSUE TITLE
Why does `mit -O` fall back so often?

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#315]
In version 49508aabbf I tried printing out `ir` whenever control flow reaches `A_FALLBACK`. Pre-guessing is enabled; all possible singleton labels were included; reject set was disabled. I ran `make-base.fs` and it made a 12M line file. In addition to the expected fallback cases (HALT, I/O) we are seeing large numbers of lines with the following `ir` values:

 - 0x1318 (NOT NEGATE, i.e. increment)
 - 0x05 (DUP)

It's possible that the DUP has an argument > 3 which is therefore not handled by the specialized interpreter, but I can't see any reason why NOT NEGATE should not be executed.

**Comment by apt1002** [comment]
We have rebased and cherry-picked the commit, such that it has become orphaned. We should give it a tag so that we don't lose it and so that other people can check it out.

**Comment by rrthomas** [comment]
Tagged `mit-O-fallback-315`.

**Comment by apt1002** [comment]
Check again and then close.

**Comment by apt1002** [comment]
The latest master, we observe 7.2M fallbacks for "4 DUP", and exactly one for "5 DUP". All the others are traps and extra instructions, as expected.

**Comment by rrthomas** [comment]
Looking at the root state (guesses made with an empty path), there are large numbers of correct guesses, but these are dwarfed by the much larger number made in other states.
