### ISSUE TITLE
Guarantee that instructions are one byte long

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#34]
SMite's instruction encoding recently changed, introducing `smite_decode_instruction()`, which returns two values:

 - a flag indicating whether the instruction is a literal or an action.
 - a value giving the literal value if it is a literal, or the opcode if it is an action.

This opened up the possibility of action instructions which are more than one byte long. No doubt that is a feature. However, it is rather inconvenient for the specialised interpreter, which now does not know how many bytes it needs to check in order to verify its guesses.

As it happens, the maximum opcode is sufficiently small that all actions do encode into one byte, as do the literals `0` and `1`. It would be helpful to guarantee that this is the case, and to provide efficient side-effect-free predicates which, given the byte value, distinguish at least these cases from each other and from other literals.

I propose that `smite_decode_instruction()` should ignore `INSTRUCTION_CONTINUATION_BIT` if `INSTRUCTION_ACTION_BIT` is set. This allows up to 128 distinct actions, and guarantees that they all encode into one byte.

I further propose adding the following macros to the public API. I think I have worked out suitable implementations; sorry for the bugs:

 - `IS_ACTION(opcode)` means `next_byte == INSTRUCTION_ACTION_BIT | opcode`.
 - `IS_SMALL_NUMBER(value)` means `next_byte == value`.
 - `IS_LARGER_NUMBER(value)` means `(next_byte & INSTRUCTION_ACTION_BIT) == 0 && next_byte > value`.

This proposal would be obviated by #28.

**Comment by rrthomas** [comment]
Closed by #46.
