### ISSUE TITLE
Remove `nextff`

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#356]
Encode `pushi` and `pushreli` with an unsigned immediate operand, and subtract off a suitable bias (32 for `pushi` and 64 for `pushreli`) before using it.

This allows `ir` to be consumed using logical right shift, and obviates `nextff`.

**Comment by rrthomas** [comment]
I explained (I'm pretty sure!) that this won't work because it breaks `jumpi`, `jumpzi` and `calli`, but then it seems we both forgot!
