### ISSUE TITLE
Merge and do away with branch instrumented_apt

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#41]
Blockers:

- [x] "make check" fails, because instrumented_apt does not implement single-stepping correctly.
- [x] "make" fails, because the "gen-actions" script requires an argument: the filename of a "labels.pickle" file telling it what control-flow graph to build.
- [x] "smite --trace" doesn't.
- [x] There should be a simple version of SMite that can easily be taught, formalized and run on small computers. This depends on #28. Also need to move optimizing code into a subdirectory of src, and allow the system to build without it (but build with it by default, and use the optimizing interpreter by default).

Desirable:

- [x] `run()` should do what `single_step()` currently does. In particular, it should `#include "instruction-actions.h"`, and it should not just call `single_step()` in a loop.
- [x] The procedure for compiling a specialised interpreter needs to be documented.
- There is currently no tool to make a "labels.pickle" file without first having an instruction trace. It is possible to work around this by using an empty trace, but there is room for improvement. We should write a tool that generates a minimal "labels.pickle" file, for boot-strapping. (Don't mind.)

Things we can add to master now to reduce the diff:

- [x] Add "actions-common.h".
- [x] Move `trace_fp` into `smite_state`.
- [x] Define `run()` directly in terms of "actions.h".

**Comment by apt1002** [comment]
The general idea is that the instrumented_apt branch adds an optimisation feature, selectable using a compile-time switch, that specialises the interpreter for running a particular smite program (or corpus of programs).

The question arises as to what it should do when the feature is disabled. Currently, smite "master" uses different code from smite "instrumented_apt". It is undesirable to maintain both versions. Instead, the unspecialised smite interpreter should perhaps be the same as the specialised one, but specialised for a trivial program.

**Comment by rrthomas** [comment]
Please do make a pull request to make the code path for `run` independent from `single_step`. (It used to do this in Beetle, for speed, and then it seemed unnecessary to compile two copies, but given the memory consumption is modest and that we're likely to want to compile several copies, never mind the RAM consumption of specialisation and other optimisation strategies, and it seems silly not to.)

**Comment by rrthomas** [comment]
> The question arises as to what it should do when the feature is disabled. Currently, smite "master" uses different code from smite "instrumented_apt". It is undesirable to maintain both versions. Instead, the unspecialised smite interpreter should perhaps be the same as the specialised one, but specialised for a trivial program.

I have no problem keeping a separate naive implementation. It's good as a reference implementation, for didactic purposes (when focusing on VM design rather than implementation), for constrained memory environments, and when security is an overriding concern.

The use of continuous integration and a good test suite should keep the maintenance burden low.

**Comment by apt1002** [comment]
I wrote "src/SPECIALISE". Its contents might be helpful for the other work items.

**Comment by apt1002** [comment]
The "instrumented_apt" version of SMite now supports "--trace".

It is now possible to bootstrap this version of SMite without using another version to help. First, compile it using an empty trace file. Then make a trace file for your chosen program or corpus. Finally, recompile using your trace file. This reduces the requirement for a tool for generating minimal "labels.pickle" file from "blocker" to "desirable".

**Comment by apt1002** [comment]
This is now done on branch feature_specializer.
