### ISSUE TITLE
BRANCH is redundant

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#5]
You could delete the BRANCH instruction, as it can be implemented as 1 BRANCHZ.

**Comment by rrthomas** [comment]
Good idea! ITYM "0 BRANCHZ".

**Comment by rrthomas** [comment]
The trouble is that in fact "BRANCH" is equivalent to "0 1 SWAP BRANCHZ", because for BRANCHZ the flag comes underneath the address. This makes sense because usually the address is known at code generation time, and the flag is computed at run-time.

**Comment by apt1002** [comment]
I see. I agree.
