### ISSUE TITLE
Inline smite_load_byte into "step.c", and maybe some others.

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#58]
This description is based on the "instrumented_apt" branch; on "master" the opportunity is the same, but the details and priorities are different.

Summary
---

"step.c" makes a lot of calls to `smite_load_byte()`: at least one per instruction executed. The compiler is not able to inline these calls because the function is defined in "storage.c", so not known until link time.

We solved this for `smite_load_stack()` and `smite_store_stack()`, which were even hotter, by manually optimizing the stack limit checks and by defining macros `UNCHECKED_LOAD_STACK()` and `UNCHECKED_STORE_STACK()`. We should do something similar for `smite_load_byte()`, which is now the hottest call.

Extra credit
---

Incidentally, the "SWAP" and "DUP" instructions still call `smite_load_stack()` and `smite_store_stack()` directly; these call sites are possibly hot enough to be worth inlining too, especially since we've done half the work.

The next hottest calls that are candidates for inlining are `smite_load_word()`, `smite_store_word()`, and `smite_rotate_stack()`, used by the "LOAD", "STORE" and "ROTATE" instructions respectively. The call to `smite_decode_instruction()` in "LITn" is also hot, but probably not worth inlining.

Further motivation
---

In the future, when we are optimizing away unnecessary pushes and pops, the benefits of inlining these functions becomes even greater. Here are the current hottest instruction sequences in pForth (the difference is the third instruction):

- ('LITn', 'CALL', 'LIT0', 'ROTATE', 'LITn', 'LIT0', 'DUP', 'LOAD', 'LIT0', 'DUP', 'LITn', 'ADD', 'LITn', 'ROTATE', 'STORE', 'LOAD', 'LIT1', 'ROTATE', 'BRANCH')
- ('LITn', 'CALL', 'LITn', 'ROTATE', 'LITn', 'LIT0', 'DUP', 'LOAD', 'LIT0', 'DUP', 'LITn', 'ADD', 'LITn', 'ROTATE', 'STORE', 'LOAD', 'LIT1', 'ROTATE', 'BRANCH')

There are a number of sub-sequences that are obviously optimizable but not without inlining functions as described above:

 - 'LIT0', 'ROTATE'
 - 'LIT1', 'ROTATE'
 - 'LITn', 'ROTATE' (if we find out what `n` is: I'm guessing 2 or -1).
 - 'LIT0', 'DUP'
 - 'LITn', ..., 'LOAD' (the value is pushed and popped unnecessarily around 'DUP').
 - 'LITn', ..., 'ADD' (similar).

Suggested approach
---

For 'LOAD' and 'STORE' it should be sufficient to move the load and store functions into a header file ("aux.h" or "smite.h"), so that the compiler can inline them everywhere the header is included.

For 'ROTATE', we should reimplement the instruction such that the "if" (testing the argument) is in "vm_data.py". That would allow code to be removed when the argument is constant, which it usually is. The case for '0' is already handled specially. Handle cases '1' and '-1' (which mean the same thing) specially too. Otherwise delegate to `smite_rotate_stack_positive()` or `smite_rotate_stack_negative()` as appropriate, and allow the compiler to inline those functions if it feels like it.

Within the rotate functions, it might be worth using a "for" loop instead of `memmove()`, to encourage the compiler to unroll the loop when the argument is small and constant. I'm not sure if that's actually a win with a real compiler, but theoretically it would allow a smart enough compiler to see that there is no aliasing.

**Comment by rrthomas** [comment]
Most of this is now done, except for the headline `smite_load_byte`, which will be resolved by changing the instruction encoding (#28).

**Comment by apt1002** [comment]
I did a measurement. Inlining `smite_load_byte()` makes the specialized smite 16% faster. Removing the memory bounds check on PC (which is unsafe, of course) gives a further 3%. In summary, shaving cycles off instruction fetch is quite significant, as expected, even if the dispatch code is unchanged.

I'm not sure how much fetch cost is left: maybe 6% of all CPU time used? 10%? We can't expect to eliminate it all, but #28 will make a big difference, as it will reduce the number of instruction fetches by a factor of about three. This is on top of the savings from inlining the call. The overall speedup attributable to reducing fetch costs will probably be a bit more than 20%.

**Comment by rrthomas** [comment]
Fixed.

**Comment by apt1002** [comment]
After improving the instruction encoding, the benefit of inlining `smite_load_byte()` has jumped to 34%. Wow!
