### ISSUE TITLE
Ideas for simplifying the instruction set

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#6]
Recording some ideas we discussed:

- [ ] HALT could be implemented as 0 STORE_HANDLER THROW.
- [ ]  ~~PUSH_PSIZE would be unnecessary on a 64-bit version of SMite.~~ It would be a shame to rule out running 64-bit SMite on a 32-bit host.
- [ ]  The PUSH_XXX instructions could be unified into a PUSH_REG instruction taking a register number from the stack. This would simplify the instruction encoding, though it does not actually remove any cases.

**Comment by rrthomas** [comment]
The suggestion to allow variable-length opcodes (#14) pretty much obviates this issue, insofar as it is really focussed on reducing the number of instructions, not on making it simpler.

I find it helpful to think of HALT as a counterpart to CALL_NATIVE; perhaps it should be called RET_NATIVE!

Closing this issue for now.
