### ISSUE TITLE
Support relocation

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#68]
In @apt1002's masterful summary:

Literal code addresses (branch targets and globals) obviously have to be PC-relative; runtime code addresses (PC, function pointers and return addresses) obviously have to be absolute. Something has to translate from the former to the latter. It could be an instruction that adds PC, or a special kind of literal instruction that adds PC, or a subroutine that adds its return address to its argument. All are reasonable, I think. A special literal would be Beetlish; a subroutine would be more SMitish.

Summary: you could do nothing in SMite, and still have pForth generate position-independent code. Alternatively, you could add a PC-relative literal instruction to SMite.

**Comment by rrthomas** [comment]
It would also be possible to reintroduce `GET_PC`, i.e. an instruction that just pushes `PC` on to the stack.

**Comment by apt1002** [comment]
Picked up in #28.

**Comment by rrthomas** [comment]
Fixed with introduction of `LIT_PC_REL`.
