### ISSUE TITLE
Compile for all supported WORD_SIZE and ENDISM combinations

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#73]
libsmite should support a range of settings without rebuilding. Compile a separate step & run function for each combination of settings.

Also see about extending to `WORD_SIZE` = 2.

**Comment by rrthomas** [comment]
Fixed instead with rebuilding.

**Comment by apt1002** [comment]
Yes, let's merge this.

**Comment by apt1002** [comment]
Let's also do one build each with WORD_BYTES=2 and INSTRUCTION_BITS=6.

**Comment by rrthomas** [comment]
Building with `--program-suffix` isn't currently useful, because it does not affect the shared library, so it's still impossible to install multiple builds side by side. Need to fix this as part of this issue; see how this was fixed for enchant (where it's the version number instead that is encoded in the shared lib).

**Comment by rrthomas** [comment]
The branch `multiple-install-73` fixes multiple installation.
