### ISSUE TITLE
Fix dependencies on instruction-{names,actions}.h

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#8]
Currently building can fail because we try to compile `step.c` and `opcodes.h` before making `instruction-{names,actions}.h`.

**Comment by rrthomas** [comment]
Fixed by commit 2dc34c44.

**Comment by rrthomas** [comment]
My mistake: fixed the Ubuntu Travis build, but not macOS.

**Comment by rrthomas** [comment]
Fixed. History rewritten so it's fixed in the commit that introduces Python scripts.
