### ISSUE TITLE
Build with ASAN before release

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#80]
Since Travis can't do this at present.

**Comment by rrthomas** [comment]
AppVeyor supports Ubuntu 18.04, so try that.

**Comment by apt1002** [comment]
There is no python3.6 package in Xenial. Could either use a PPA (deadsnakes or jonathonf) or do it on AppVeyor.

`asan-issue80` branch is the attempt to do this on Travis.

**Comment by rrthomas** [comment]
Done!
