### ISSUE TITLE
Make Event a superclass of Action.

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#85]

**Comment by apt1002** [comment]
It's beginning to look like Events and Instructions (as Actions are now called) will be in one-to-one correspondence. Event currently has some extra fields, but perhaps we can aim to delete class Event? That would be great.

**Comment by rrthomas** [comment]
We can revisit this when we merge instrumented_apt.

**Comment by apt1002** [comment]
Class event has been deleted, as events are now in 1:1 correspondence with Instructions.

**Comment by apt1002** [comment]
Class event has been deleted, as events are now in 1:1 correspondence with Instructions.
