### ISSUE TITLE
DUP and STORE are the only stack operations needed.

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#86]
Forth:
POP = 0 STORE
n SWAP = 0 DUP n+1 DUP 2 STORE n+1 STORE
n ROTATE_UP = n DUP (i+1 DUP i+3 STORE for i in reversed(range(i))) 1 STORE
n ROTATE_DOWN = 0 DUP (i+2 DUP i+2 STORE for i in range(n)) n+1 STORE

C:
Temporaries are on top of the stack, then locals, then return address, then arguments.
To initialize a variable, compute it into a single temporary, then designate it as a local.
To leave a scope, POP some locals.
To read a local, DUP it into a temporary.
To assign a local, STORE a temporary over it.
Function calling convention: push args, CALL (i.e. push return address). On exit, args and return address are removed and replaced with the results.

**Comment by apt1002** [comment]
Actually, POP = –1 STORE (which is disallowed) under the convention of #87.

You can achieve POP using 1 DUP 0 STORE 0 STORE, but it doesn't work for the last item on the stack, and it is ugly. Better to provide POP.

**Comment by apt1002** [comment]
Rename DUP to LOAD so it looks like a pair with STORE? Anyway, aren't the names LOAD and STORE already used for memory access instructions?

Rename POP to DROP so it is clear that the value is discarded?

**Comment by apt1002** [comment]
I'm still wondering which of STORE and SWAP we should provide. STORE = n SWAP POP, which is more convenient than n SWAP = 0 DUP n+1 DUP 2 STORE n+1 STORE. Also, ROTATE_{UP,DOWN} are easier to express using SWAPs than using DUPs and STOREs. SWAP is also the mathematically prettier choice. However, STORE is more common than SWAP and matches hardware better.

We should perhaps choose in order to reduce the number of instructions executed. I think SWAP wins by that criterion.

**Comment by rrthomas** [comment]
Fixed.
