### ISSUE TITLE
Cleverer stack pictures

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#87]
Of the SMite instructions, only stack operators access the stack directly, that is, use `smite_load/store_stack` in their action code. We would like to generalise stack pictures so this is unnecessary.

For variadic instructions, the top stack item on entry is the number of variadic items; the remaining items can be named, except that one, in any position, called `ITEMS`, represents the variadic items. This allows all the stack operations to be expressed with no action code, as follows:

POP = [ ITEMS count ] => []
DUP = [ x ITEMS count ] => [ x ITEMS x ]
SWAP = [ x ITEMS y count ] => [ y ITEMS x ] # note: this changes the meaning of count!
ROTATE_UP = [ x ITEMS count ] => [ ITEMS x ] # note: the ITEMS move!
ROTATE_DOWN = [ ITEMS x count ] => [ x ITEMS ] # they moved again!

**Comment by rrthomas** [comment]
Additional suggestion: extend type annotations to the core, to capture types such as signed, unsigned, and aligned address. This would mean the machinery for handling types would be in the core, but not the machinery for handling stack items of non-word size (except of course variadic items).

**Comment by apt1002** [comment]
Why?

**Comment by apt1002** [comment]
I'm thinking more about type annotations, and in particular about what it would be like to reimplement SMite in another language.

I can see the value in the form-filling style. It forces you to make some conscious decisions where they are required, e.g. whether an alignment check is necessary. It reduces O(n) code (where n is the number of instructions) to O(1) code (though I'm not sure that's a win in this case). There might be a readability win too.

The alternative design is: just hand over the bits. Then, all the type-specific stuff has to be written in the action code, or (in the case of the alignment checks) in the code which the action code calls. I think that's simpler, and possibly easier to understand (since the details are written in C, a widely known language, rather than using our made-up annotations). I think this division of declarative and non-declarative code is likely to be more language portable; C's type system is somewhat esoteric.

I don't really mind either way, but I don't think type annotations are a big win.

I think handling variadic instructions is a big win, in contrast.

**Comment by rrthomas** [comment]
The big picture is that this is part of FFI. Type annotations could use different type systems, for example IDL for Web IDL, if implementing SMite in WebAssembly.

The core picture is that I am aiming to ensure that the core doesn't have to know anything about this (so for example TypedStackPicture will report depths as ints, and if necessary split argument and result names into multiple names). But this is all stuff that makes writing C extensions easier now, and will in any case be needed in some form for full-on FFI.

**Comment by rrthomas** [comment]
I have now done this. In the end it seemed globally simpler to make the core know about different types. I think this can be used to advantage for byte load/store and to allow an unsigned/signed distinction; it would also be handy for float support. I suggest reviewing the code for familiarity. It can certainly be improved (in particular, I think it's worth discussing the balance between dumb code plus selective disabling of warnings versus smarter code generation where the output is easier to read; there are also some potential pitfalls in the current version for the optimizer; however, that all falls under #107).

**Comment by apt1002** [comment]
This worked out well. I'm happy to have typed stack items in the core if they are managed like this.

I noticed one "regression" and one deviation from the design.

The regression is that the depth of a stack item is not known to Python, as it is computed as a C expression (a Python str). This might make it difficult to cache items in C locals. Do you have a plan?

The deviation is in the definition of `COUNT`. Above, we said it would be the number of ITEMS, but it's been implemented as the number if items underneath COUNT minus one. This makes a difference for SWAP.

**Comment by rrthomas** [comment]
Statically computing depths: can certainly put more effort into doing this, so that it's an `int` until it involves `COUNT`.

Meaning of `ITEMS`: done.

**Comment by apt1002** [comment]
Great!
