### ISSUE TITLE
Tuning gen-labels

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#88]
In gen-labels.walk, try to guess a good value for the tuning parameter (currently 30000).

**Comment by apt1002** [comment]
The optimal tuning depends on the length of the instruction trace used to train the predictor. It has also changed as we've reduced the number of instructions generated per label. The number of labels in the optimally-tuned `run_specialized()` has increased, but the code size has remained roughly unchanged throughout, at a few dozen KB. It seems plausible that the instruction cache limits performance if we over-specialize.

**Comment by rrthomas** [comment]
Current options therefore seem to be:

- Make the parameter mandatory, to point up the fact that its best value changes all the time
- Try to devise a sensible formula based on your observations above

Any other ideas?

**Comment by apt1002** [comment]
I choose the latter. On it.

**Comment by apt1002** [comment]
Branch "issue88" has a version of gen-labels that always uses the 1500 most common paths. I hope this heuristic will be more robust, especially to changing the length of the trace file.

**Comment by rrthomas** [comment]
Fixed by #206.
