### ISSUE TITLE
Remove relics of tracing from Python SMite bindings.

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#93]
The Python SMite library is not capable of generating instruction traces, but there are docs and extra keyword arguments left over from an earlier, more innocent age in which it could.

**Comment by rrthomas** [comment]
This is a misunderstanding: "trace" in the context of the Beetle shell means "single-stepping while outputting information for each instruction": the PC, I and A registers. I don't remember using it much, though. It looks like I never quite finished implementing it in the Python version of the shell, and I am happy to remove it.

**Comment by apt1002** [comment]
Done.
