### ISSUE TITLE
Add `init` to core spec

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#99]
I think this is a sufficiently important function that it should be added to the core spec.

Also note that currently there's a hole in the spec: it says that `run` and `single_step` do not perform initialisation (correct), and that registers may not be accessed directly but only via code (not actually true in C SMite). I think it's entirely reasonable to allow access to the registers (I think I'd make the register accessor functions public in the C API, but not mandate functions vs direct object access in the spec). C SMite also makes most registers read-only, because they should be changed via APIs (e.g. MEMORY, STACK_SIZE). I'm not sure whether it's worth specifying that or just being vague: in particular, in better languages than C it might be reasonable to perform stack/memory reallocation by changing the value of that register rather than a reallocation function.

**Comment by apt1002** [comment]
I think you should write the accessor functions. You can probably auto-generate them.

**Comment by rrthomas** [comment]
They already exist and are auto-generated. I'm talking about whether they should go in the spec.

**Comment by apt1002** [comment]
I see.

I suppose it depends on what the spec is for. If it's mainly to encourage other compatible VMs to run SMite code, then there is no need for register access functions to be in the spec. If it's to encourage ports of SMite to provide a similar C API then perhaps there is.

I think you're after the former, in which case my answer is no: be vague.

**Comment by rrthomas** [comment]
You're right, I'm after the former. It's about just the VM, not the C API (that's why it's language neutral). Sounds like it's just `init` that should be added, then.

**Comment by rrthomas** [comment]
(Done.)
